### ISSUE TITLE
Figure out how to do SQLite versioning/migrations

### ISSUE THREAD

**Issue by skrytt** [skrytt/catnip#14]
We will need to be able to modify the database schema in order to store additional data. To do this, we will need to find a workable approach to database versioning and upgrades/downgrades of the schema. This ticket is to track those efforts.

**Comment by skrytt** [comment]
Working on this with https://github.com/skrytt/catnip/pull/26/files .

**Comment by Conundris** [comment]
@skrytt you can also reference PRs looks like this #26
