### ISSUE TITLE
User commands for Server - Color chooser

### ISSUE THREAD

**Issue by Conundris** [skrytt/catnip#31]

**Comment by skrytt** [comment]
This crossed my mind also. One concern is that if the chosen solution requires the bot to create roles with new colours, this becomes a permissions challenge (must guarantee bot cannot give extra perms on top of what a user already had).

**Comment by alexisnotonffire** [comment]
Would this work?
1. User requests colour x
1. Bot converts x to hex
1. Bot reads user's full permissions
1. Bot hashes combination of colour and permission
1. Bot creates role with hash if not already there
1. Bot adds user to hash
1. Bot removes current role if non-default and empty.

Seems like it meets needs but role names would be messy. Is this likely to be a problem? Hex should also be abandoned if there is a role limit for server and use something more restrictive.

**Comment by skrytt** [comment]
@alexisnotonffire The role limit per guild is 250 AFAICT (though in my brief search I couldn't find recent documentation on it). Ideally I would like to avoid allowing regular users to instruct the bot to create new roles

I would be more comfortable with allowing users to select a pre-existing colour (perhaps we can say that any role with a name beginning with `colour` is a colour role?). I would imagine it might work like this instead:

1. User requests colour `x`
2. Bot tries to find role named `colour-x` and finds a matching role
3. Bot searches user's existing roles for roles prefixed with `colour` and unassigns those roles (to avoid role priority issues that might prevent the new colour from showing)
4. Bot assigns role `colour-x` to the user

For step 2, ideally if the bot does not find a matching role, it would display an error message to the user in response.

What are your thoughts?

**Comment by alexisnotonffire** [comment]
@skrytt Sounds fair. I'll do matching with
1. Transform `x` into one lowercase word `X`.
1. Pattern match `colour-X` against guild roles.

**Comment by Conundris** [comment]
@skrytt One thing to note if you do go for a looking for a colour via the command is to make sure to keep a consistent naming standard. Something in the lines like this maybe [Html Color Names](https://htmlcolorcodes.com/color-names/).

Do we want to have the error outputs for this on the server though? An option might be to whisper this to the user directly? Also with this route we'll need a list available colour command (most likely embed the list of those for formatting reasons to have it not be a enormous list somewhere and maybe also per whisper to user).

Besides that the flow looks good.

**Comment by alexisnotonffire** [comment]
I think the bot may need the manage role permission to set user colours. I know you said specifically you didn't want it to have this so maybe we accept this can't be done or we find an alternative.

**Comment by skrytt** [comment]
Ah @alexisnotonffire to clarify:
- I'm happy for the bot to assign or unassign roles that already exist to members of the guild
- I'd not be happy with the bot creating roles or deleting roles

**Comment by skrytt** [comment]
@Conundris: I'm okay with either option (pm error text to user or message error text to the channel). What are your specific concerns about having the errors printed to the channel? One advantage to doing that is that other users can watch and learn/help if that is required. (Note I don't feel strongly either way; however, I would like to establish whatever we choose as a standard that we follow for future features)

**Comment by alexisnotonffire** [comment]
What I mean is that while I'm not actively making the bot create roles, the permission it needs gives it the capability to. I was unsure whether this would be okay.

Regarding the standard, let me know what you decide as currently my code does neither. The errors are logged server side with command error and no failure is communicated back to the user anywhere.
